### ISSUE TITLE
Support Java 8 runtime standard projects

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/google-cloud-eclipse#1057]
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/946

If Eclipse is doing any validation/warning based off of Java 8 usage in Java standard, it should make sure that it does not complain for cases where the user has configured
appengine-web.xml:
`<runtime>java8</runtime>`

**Comment by briandealwis** [comment]
- [ ] update to latest appengine-plugins-core (0.2.9)
- [ ] add feature flag for Java 8 support
- [ ] add Java 8 support to standard facet
- [ ] configure launch configuration JRE?
- [ ] add support for pulling JRE from the launch configuration?
- [ ] identify and fix all Java 7 assumptions :-)

**Comment by briandealwis** [comment]
Skimming through the user guide:
  - existing apps should work unchanged
  - supports Servlet 3.1 spec (still compatible with 2.5); but async is _not supported_
  - much of JDK whitelisting no longer applies, though there are constraints on using new processes and Servlet 3.1 async

**Comment by ludoch** [comment]
On Mar 31, 2017 17:49, "Brian de Alwis" <notifications@github.com> wrote:

Skimming through the user guide:

   - existing apps should work unchanged
   - supports Servlet 3.1 spec (still compatible with 2.5); but async is *not
   supported*

Yet, we are looking at this now. Might come after 9.4.3 jetty upgrade.


   - much of JDK whitelisting no longer applies, though there are
   constraints on using new processes

Bug will be fixed in the following push. Do not change the eclipse editor
for that...


   - and Servlet 3.1 async

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1057#issuecomment-290750723>,
or mute the thread
