### ISSUE TITLE
Maven wizard more like eclipse standard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1079]
Here's the standard Eclipse new Maven project page:

![image](https://cloud.githubusercontent.com/assets/1005544/21012797/ba105e5c-bd25-11e6-8439-dacbc4e4c233.png)

![image](https://cloud.githubusercontent.com/assets/1005544/21012837/df744320-bd25-11e6-89f9-4cd81f6785e7.png)

![image](https://cloud.githubusercontent.com/assets/1005544/21012616/ed442ec6-bd24-11e6-9677-108dd1e5e2f5.png)

Some thoughts:

1. Should our wizard also ask for name and description?
2. Should version/group ID/artifact ID be popups?
3. Should we ask for parent project IDs?
4. Group name: Maven project coordinates --> Artifact
5. They put workspace location on a separate page.
6. They offer the option to create a simple project with no archetypes.
7. Their archetype selection happens before the entry of Maven coordinates. 

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.google.foo</groupId>
  <artifactId>fred</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>foo</name>
  <description>bar</description>
</project>

**Comment by briandealwis** [comment]
I actually find the maven wizard pretty confusing, particularly around (7), but also (5)-(6) too: why do I only put in artifact identifiers in the 2nd or 3rd page?  

The drop-downs for Artifact ID, Group ID, and Version might be useful.  They'd be much more useful if they were repopulated with values from the other projects in my workspace, rather than just the projects that _I_ had created previously.
