### ISSUE TITLE
Enable Google code style checking

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/google-cloud-eclipse#109]
See: GoogleCloudPlatform/app-tools-lib-for-java#17

**Comment by briandealwis** [comment]
Seems that hosting the files within a dependency requires first installing that dependency — maven doesn't resolve dependencies within the project

https://github.com/m2e-code-quality/m2e-code-quality/issues/40

**Comment by briandealwis** [comment]
I have the Travis infrastructure set up to verify checkstyle checks on commit in [`wip-checkstyle-109`](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/tree/wip-checkstyle-109); it's currently failing as our code doesn't comply.  But there are some discrepancies between the [Google Java Style guide](https://google.github.io/styleguide/javaguide.html)], as implemented in the [Google Checkstyle settings](http://checkstyle.sourceforge.net/google_style.html), and the provided [Eclipse Formatter settings](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml#L59), and the style settings from GPE.

Work remaining:
- [ ] Reconcile out existing settings and the Eclipse Formatter settings to the Checkstyle settings
- [ ] Document how/where to get the Checkstyle plugin for Eclipse and its configuration
- [ ] Document any further configuration that may need to be done
- [ ] Reformat the code in the repository

**Comment by briandealwis** [comment]
Look at using Oomph to set up workspace defaults.

**Comment by briandealwis** [comment]
I became aware of a new Maven plugin called the [`eclipse-settings-maven-plugin`](https://github.com/BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin), and it's pretty nifty.  It requires:

  1. Deploy a common set of `.settings/` files as a Maven project to some Maven repository (e.g., to Maven Central or hosted from our GCS location).
  2. Configuring our Maven setup to invoke the `eclipse-settings-maven-plugin`, referencing the settings usually bound to the `generate-sources` lifecycle phase.

When building, the plugin overwrites the project settings with those from the settings project.   (Note, there's [one bug fix pending](https://github.com/BSI-Business-Systems-Integration-AG/eclipse-settings-maven-plugin/pull/5) that's required to work nicely with m2e.)

I've pushed up a [POC](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i109-settings) that defined a project in `eclipse/settings/` to provide the _GoogleStyle_ formatter and cleanup settings as used by GPE.  As `eclipse-settings-maven-plugin` doesn't try to resolve the specified settings project from the source repository, you need to first do something like `cd eclipse/settings && mvn install` before a build.  On the flip side, it would probably make more sense to have a canonical set of Google settings that are referenced from Maven Central.

Another thing to note: the [Google Java Format](https://github.com/google/google-java-format) project now has an Eclipse plugin.  Unfortunately it is only [available as a .jar](https://github.com/google/google-java-format/releases) rather than an update site, and so Eclipse's install UI doesn't support installing it from within the IDE.  But it can be downloaded and put into your Eclipse installation's `dropins/` folder.

**Comment by briandealwis** [comment]
Note that the build is failing on this branch as I enabled the _error on non-externalized strings_, and we have lots of such strings.
