### ISSUE TITLE
CloudSdkPreferenceArea.doCheckState gets called twice on every change

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1215]
In the debugger I noticed that CloudSdkPreferenceArea.doCheckState gets called twice on every change to the directory field, once on key up and once on focusLost

**Comment by chanseokoh** [comment]
Looks like this is because you lose focus when your debugger is activated. For verification, I set a non-stopping breakpoint at `doCheckState()` that just logs the by-passing control ([with this trick](https://rgrunber.wordpress.com/2016/12/09/hot-code-replace-with-the-breakpoint-properties-page-in-eclipse/)). I see when I enter one character, the method is called once. I think we can close this issue?
