### ISSUE TITLE
Handle the case when the user has an older App Engine library available locally

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1233]
#830 #1176 
We should handle this somehow. One option is to show a build warning, and allow the user to fix it via a quick fix that downloads the latest version. The warning could be configurable from preferences.

**Comment by elharo** [comment]
This should not be more than a warning. A quick fix is a good idea if it's not too much effort to implement. We do need to consider that the user may have deliberately chosen an older version of a library.

**Comment by briandealwis** [comment]
The crux of the issue is that the user doesn't actually select a version.  It seems to me that the native projects are really only useful for small projects or prototypes where they just want to run against the latest stable versions.  If they want further control over particular versions, then they should use Maven (or Gradle).

**Comment by elharo** [comment]
moot given changes to dependency management
