### ISSUE TITLE
Move AppEngineDescriptor.java to appengine-plugins-core

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1269]
[plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/AppEngineDescriptor.java](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.util/src/com/google/cloud/tools/eclipse/util/AppEngineDescriptor.java)

**Comment by patflynn** [comment]
@elharo This is not useful for IJ since we already have JB native introspection into XML: https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/master/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/descriptor/dom/AppEngineStandardWebApp.java

We also don't want the OSGI deps in IJ or Maven/Gradle

**Comment by elharo** [comment]
The appengine-plugins-core version will not include any OSGI or Eclipse packages.
