### ISSUE TITLE
"Invalid bucket name" error message in deploy preferences is not helpful

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1324]
You get this error message until you type at least three characters. We should message that the bucket name should be at least 3 characters initially.

![selection_003](https://cloud.githubusercontent.com/assets/10523105/22442881/dd4bab42-e70a-11e6-806c-e235851145d5.png)

**Comment by akerekes** [comment]
Salvaging this message could be useful: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1303/files#diff-780e152377fa015580e0af5dd657d017L2

**Comment by elharo** [comment]
Maybe we shouldn't show a message until a second or two after the user has stopped typing? And if we do show a messages it would more clear about what the problem is; e.g. two few characters. However we should not use a catch all message that lists everything that could be wrong. E.g. don't tell the user the name can't contain whitespace is it doesn't contain whitespace.

**Comment by elharo** [comment]
I'm marking this low priority since most users will never see or touch this field.

**Comment by JoeWang1127** [comment]
close as not planned
