### ISSUE TITLE
Do we need MappingDiscoveryJob or not?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1327]
This todo remains in CreateMavenBasedAppEngineStandardProject. If we do need the  MappingDiscoveryJob remove the todo. If we don't, remove the job. 

   /*
     * invoke the Maven lifecycle mapping discovery job
     *
     * todo: is this step necessary? we know the archetype contents and we handle the
     * lifecycle-mappings and rules
     */
    Job job = new MappingDiscoveryJob(archetypeProjects);
    job.schedule();

**Comment by elharo** [comment]
FYI, what this seems to do in practice is add Maven entries to the Run As menu:

![image](https://cloud.githubusercontent.com/assets/1005544/22478162/d4d8dc80-e7b6-11e6-89ab-ac245fb27bf1.png)

So the question becomes, do we want these or not? If yes, ditch the TODO. If not, remove the code. Thoughts solicited.

**Comment by briandealwis** [comment]
The discovery job looks through the referenced Maven plugins and goals and prompt the user for to fetch and install any necessary configurators (e.g., as seen on first-import of our projects for the Tycho plugins).  It's a necessary part of importing a Maven project (pic below).

That said, we define these archetypes and our plugin defines lifecycle mappings for what's found so that there should be no unbound goals.  The only question then is: is it possible for the archetypes to be updated before we can adapt CT4E to those changes?  (Hmm… perhaps we should move the lifecycle bindings we define in our plugins into the archetypes as project settings?)

<img width="670" alt="687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f66627269636f6e2f666f6c646572732f4a696e672f6d656469612f37383637663761332d643462372d346132302d393866362d3363323134646264646662372f30303030303031382e706e67" src="https://cloud.githubusercontent.com/assets/202851/22495027/aca85908-e80a-11e6-9fd3-8197b32f7718.png">

**Comment by elharo** [comment]
If it makes a difference, I'm considering whether we should break our dependency on the archetypes project; and bundle our own templates more directly.
