### ISSUE TITLE
Select Project after creation?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1418]
1. Select project in project explorer.
2. Create new project.
3 Previously selected project is still selected.

Does this make sense or should we select the newly created project?

![image](https://cloud.githubusercontent.com/assets/1005544/23022626/e04ea4bc-f41f-11e6-8c74-577038179acb.png)

**Comment by hray2003** [comment]
That's a great question. It feels like more common to see the newly created object gets auto selected.

In this case I'd be curious to know
1. What's the goal of creating a new project in most cases. If the newly created project is not auto selected, will most users then have to select it in order to work on it?

2. If the newly created project does get auto select, should there be concern anything gets lost on the previously selected project? 

I tend to think if user's focus/intention is already on the newly created project, then landing on the previously selected project might be disorienting.

**Comment by akerekes** [comment]
I think it's OK to not select the project. The little double arrow icon in `Project Explorer` links the editor with the explorer so if I open a new editor, it will find the corresponding file in the explorer and select it. In case it is not pushed in, I can open a file while the selection is on a different project. So I think users are accustomed to having/not having the explorer and the editor in sync, and it's their deliberate choice.

**Comment by briandealwis** [comment]
I agree with @akerekes.  More importantly, I don't think there's a way to force the _Project Explorer_, or any explorer, to select the project.
