### ISSUE TITLE
Report Bug from Inside Eclipse

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1458]
**Help > Report Bug or Enhancement**

![image](https://cloud.githubusercontent.com/assets/1005544/23234545/68ecbe08-f920-11e6-91e3-059bf4e053ec.png)

**Comment by akerekes** [comment]
I'm struggling to find some documentation on how to do this, but found the exsd for the extension point:

https://github.com/eclipse/mylyn.tasks/blob/master/org.eclipse.mylyn.tasks.bugs/schema/support.exsd

**Comment by chanseokoh** [comment]
It's perplexing why the extension point is provided by Mylyn, which seems to be an integrated personal/team task management tool.

In any case, similar to AERI, the `org.eclipse.mylyn.tasks.bugs` bundle is available starting from Neon. I cannot find it under the "plug-ins" view in Mars.

**Comment by chanseokoh** [comment]
Oops, it was just that the `org.eclipse.mylyn.tasks.bugs` bundle wasn't in our target platform. It's available on Mars.

**Comment by chanseokoh** [comment]
I did make some progress despite almost no existence of documentation. However, initially I thought I would open our GitHub repo issue tab, but it looks like I am forced to go through Mylyn's "Task" work flow to submit a bug:

![selection_001](https://cloud.githubusercontent.com/assets/10523105/24121560/11647eae-0d8f-11e7-993e-1d31e9e27dc5.png)

I will continue to explore if I could get away from the "Task" flow and somehow open an arbitrary URL. However, if it turns out we can't do it, I think it will take substantially more time to implement this feature.

**Comment by elharo** [comment]
If it's too difficult we could just add a menu item to our toolbar button: Report a bug in Cloud Tools for Eclipse that opens an arbitrary URL.

**Comment by chanseokoh** [comment]
I like the menu item approach. IMO, that gives more visibility.
