### ISSUE TITLE
Run tests in randomized order

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1520]
We should run our tests in randomized order to discover any interference between them, see [tycho-surefire-plugin docs](https://eclipse.org/tycho/sitedocs/tycho-surefire/tycho-surefire-plugin/test-mojo.html#runOrder)

**Comment by elharo** [comment]
Would this make things flakier and harder to reproduce if there is an order dependence? Is it possible to reproduce a failing build including order?

**Comment by briandealwis** [comment]
The default is to run tests in [filesystem order](https://eclipse.org/tycho/sitedocs/tycho-surefire/tycho-surefire-plugin/test-mojo.html#runOrder), which should be somewhat deterministic on Travis since Travis starts the container from scratch.

But Tycho Surefire also supports "hourly" which might be best for us: _alphabetical on even hours, reverse alphabetical on odd hours_.

**Comment by elharo** [comment]
Is it possible to add an extra run to the existing group of neon/oxygen/mars that would run tests in random order? That is, the existing groups would always run in the same order but we'd have one in random order? or even/odd order?

I wouldn't want to do this until we've resolved the 143 flakiness issue.
