### ISSUE TITLE
Build path contains duplicate entries in Java Project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1558]
1. Create a Java project (not a GCP project)
2. Add all 3 App Engine Libraries to project
3. Get this error dialog:

![image](https://cloud.githubusercontent.com/assets/1005544/23719119/138043ca-0408-11e7-9c4e-e762d5303301.png)

Despite the error, the entries appear to have been added anyway.

**Comment by chanseokoh** [comment]
This happens also on App Engine projects too, and I think I know why:

1. `BuildPath.addLibraries()` explicitly sets the new libraries by calling `javaProject.setRawClasspath()`.
2. We make `AppEngineLibrariesPage.getNewContainers()` return the libraries that we just added (`return added;`). However, interestingly, the underlying framework will add the libraries we return, which we already added. That's why we get the error message. (I find that this behavior isn't clear from its Javadoc.)

So, we could either 1) don't explicitly add the libraries in `BuildPath.addLibraries()`; or 2) simply return `null` from `AppEngineLibrariesPage.getNewContainers()`.

The option 1) seems to break new project wizards, so we may want to go with 2).

**Comment by elharo** [comment]
I now have this firing 100% of the time at head so we need to fix this before release. I'm nervous about making getNewContainers() return null since that violates the interface contract. This may need a little refactoring so that we only call javaProject.setRawClasspath() from the new project wizards.

**Comment by chanseokoh** [comment]
+1 for refactoring.
