### ISSUE TITLE
something with our release tagging is screwy

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1563]
This didn't used to be necessary. Figure out how we need to change the release process to avoid this. 

>-  Push the release branch to github: `git push origin <this_release_name>`
>    - If you have the tag with the same name locally that you created earlier, git will complain with an error `error: src refspec <some_name> matches more than one.` In that case, delete the local tag with `git tag -d <same_tag_name>` first.

**Comment by chanseokoh** [comment]
My gut feeling about how this can happen:

1. We create a tag with a certain name, e.g., "v1.2.3" on the origin repo (which is done on GitHub).
2. Locally, if you do `git pull` or `git fetch`, the tag "v1.2.3" is fetched, and the name is now registered in your local repo.
3. You create a local branch with the same name "v1.2.3". (No problem creating a branch with the same tag name, because these are two different things.)
4. When you try `git push origin v1.2.3`, `git` complains because it doesn't know if you are trying to push the tag or the branch. (FYI, you can do `git push --tags` to specifically tell it's a tag.)

So, if you do 1 after 2, or if you don't do 2, you won't have this problem. However, if you tag first and then pull, you will end up having two refs with the same name, which could cause ambiguity.

**Comment by chanseokoh** [comment]
Answers in this SO question make sense to me: http://stackoverflow.com/questions/9378760/git-push-local-branch-with-same-name-as-remote-tag

**Comment by elharo** [comment]
seems we simply need to not create a branch. Instructions updated.
