### ISSUE TITLE
Job "Stopping App Engine Standard at localhost" does not die when server goes down by deleting a project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1729]
1. Create a HelloWorld project.
2. _Run As_ > _App Engine_. The server state will become `[Started]`.
3. Delete the project.
4. The server will stop automatically, and its state will become `[Stopped]`. However, a job called "Stopping App Engine Standard at localhost" will not die. Cancelling the job has no effect either.

**Comment by briandealwis** [comment]
Fixed by #2775

**Comment by chanseokoh** [comment]
I don't think this is fixed. The server has been going to the "[Stopped]" state correctly. It is the Eclipse job that lingers on.

**Comment by briandealwis** [comment]
Oops!

**Comment by briandealwis** [comment]
So that _Stopping_ job is [waiting for the server to be marked as stopped](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3667) using a Java monitor.  There's [a server listener](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3588) that notifies the monitor when the server is changed into a stopped result.  But it looks like there is a race condition where the job may wait on the monitor after the server has been marked as `STOPPED`, so they've introduced a [_Server Stop Timeout_ thread](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3620) that periodically notifies the monitor after a configured timeout.

So the _Stopping_ job does *eventually* end due to the _Server Stop Timeout_  job, but it looks like there's a bug in the timeout thread: it wakes every second, but doesn't actually do anything and so  ends up waiting the full timeout period of 240s:
```
						while (totalTimeout > 0 && !timer.alreadyDone){
							Thread.sleep(retryPeriod);
							if (serverTimeout > 0)
								totalTimeout -= retryPeriod;
						}

						if (!timer.alreadyDone) {
							timer.timeout = true;
							// notify waiter
							synchronized (mutex) {
								if (Trace.FINEST) {
									Trace.trace(Trace.STRING_FINEST, "stop notify timeout");
								}
								mutex.notifyAll();
							}
						}
```
A similar pattern is used elsewhere in this class but they notify the mutex so as to wake the associated job.

Since the _Stopping_ job will end eventually, and this situation (deleting projects whilst the server is running) is pretty rare, I'm going to close this and open a bug against WTP.

**Comment by briandealwis** [comment]
While writing up a bug against WTP, I did some more digging and discovered that my hypothesis is incorrect.

It turns out [we stop the server](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerDelegate.java#L257) when there are module changes and there are no modules remaining.  In this case, we're dealing with a ServerWorkingCopy instance (because the server definition is being modified).

```
Thread [ModalContext] (Suspended (entry into method stop in Server))	
	ServerWorkingCopy(Server).stop(boolean) line: 1911	
	LocalAppEngineServerDelegate.modifyModules(IModule[], IModule[], IProgressMonitor) line: 259	
	ServerWorkingCopy.modifyModules(IModule[], IModule[], IProgressMonitor) line: 553	
	ServerUtil.modifyModules(IServerWorkingCopy, IModule[], IModule[], IProgressMonitor) line: 398	
	JavaEEServerRefRefactorParticipant.updateServerRefs(IModule[], IServer, IProgressMonitor) line: 53	
	JavaEEServerRefRefactorParticipant.access$1(JavaEEServerRefRefactorParticipant, IModule[], IServer, IProgressMonitor) line: 41	
	JavaEEServerRefRefactorParticipant$RemoveProjectFromServersChange.perform(IProgressMonitor) line: 180	
	CompositeChange.perform(IProgressMonitor) line: 280	
	ProcessorBasedRefactoring$ProcessorChange(CompositeChange).perform(IProgressMonitor) line: 280	
	PerformChangeOperation$1.run(IProgressMonitor) line: 257	
	Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor) line: 2240	
	Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2267	
	UIPerformChangeOperation(PerformChangeOperation).executeChange(IProgressMonitor) line: 305	
	UIPerformChangeOperation.executeChange(IProgressMonitor) line: 96	
	UIPerformChangeOperation(PerformChangeOperation).run(IProgressMonitor) line: 216	
	Workspace.run(ICoreRunnable, ISchedulingRule, int, IProgressMonitor) line: 2240	
	Workspace.run(IWorkspaceRunnable, ISchedulingRule, int, IProgressMonitor) line: 2267	
	WorkbenchRunnableAdapter.run(IProgressMonitor) line: 86	
	ModalContext$ModalContextThread.run() line: 119	
```
This eventually calls Server#stopImpl(), which installs a server listener, tells the `ServerBehaviourDelegate` to stop, and then waits on a monitor.  The server listener notifies the monitor when the server is stopped.

Our `ServerBehaviourDelegate` implementation, `LocalAppEngineServerBehaviour`, asks the devappserver to quit, and then calls `setServerState(STATE_STOPPED)`.  This eventually triggers the _Stopping_ server listener [which compares the server instance vs the event instance](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3594).  But in this case, the call to `Server#stopImpl()` was made against a `ServerWorkingCopy`, but the actual `STATE_STOPPED` event raised by `LocalAppEngineServerBehaviour` is _against a `Server` instance_.

And the _Stopping_ server listener is unique in that it [filters the events by comparing the server instance to the event server instance](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3594):

   if (Server.this == server && (state == IServer.STATE_STOPPED || state == IServer.STATE_STARTED)) {

And so the listener doesn't notify the _Stopping_ job of the change.

- - - -

But it actually seems odd that we're stopping the server in `modifyModules()` as we need to stop or restart the server if there is *any* module change.  I expect that there is some callback or setting for WTP to restart the server.

**Comment by briandealwis** [comment]
So I've been going round and round on this for a bit trying to figure out the right way to do this.

Deleting a web-module project triggers the WTP-JST `JavaEEServerRefRefactorParticipant` to remove any deleted modules from any servers.  It basically does the following:
```
   for(int i = 0; i < moduleToRemove.length) {
      IServerWorkingCopy wc = affectedServer.createWorkingCopy();
      List list = Arrays.asList(affectedServer.getModules());
      if (list.contains(modulesToRemove[j])) {
        ServerUtil.modifyModules(wc, null, new IModule[]{modulesToRemove[j]}, null);
      }
      IServer newServer = wc.saveAll(true, null);
      int state = newServer.getServerState();
      if(state == IServer.STATE_STARTED) {
         newServer.publish(IServer.PUBLISH_INCREMENTAL, new NullProgressMonitor());
      }
   }
```
So it only publishes changes through *if the server is currently running*.  `PUBLISH_INCREMENTAL` is a _publish-kind_, and there are three real types here:
  - `PUBLISH_INCREMENTAL` means publish anything changed
  - `PUBLISH_FULL` means publish all modules regardless of change
  - `PUBLISH_CLEAN` means remove everything first and then publish like `PUBLISH_FULL` 

`IServer#publish(int publishKind)` delegates to `ServerBehaviourDelegate#publish(int publishKind)`, which acts as the publishing orchestrator.  It performs the following steps:
  1. It first compares the server's current configuration (i.e., post-`modifyModules()`) to the last-published state to determine the list of web-modules and their change state (aka _delta kind_: `ADDED`, `REMOVED`, or `CHANGED`).
  2. It then calls out to any configured _task delegates_ with the modules and delta-kinds to generate a set of publishing tasks (called publishing operations); these aren't executed yet.
      - Our `LocalAppEnginePublishTaskDelegate` constructs and returns a list of `LocalAppEnginePublishOperation` instances for each module.
  3. It then calls `publishStart()`.
  4. It then calls `performTasks()` to executes all of the publishing tasks (the publish operations) obtained in Step 2.
      - Our `LocalAppEnginePublishOperation` basically pushes the module into server staging directory: it removes the module on `PUBLISH_CLEAN` or if the module is `REMOVED`, and it re-publishes changes within a module into the server staging directory on `PUBLISH_FULL`.
      - The devappserver complains when removing the staged module as the `appengine-web.xml` disappears.
  5. It then calls `executePublishers()` to any configured publisher-delegates.  Tomcat uses one to generate their context descriptor.
  6. It then calls `publishServer(publishKind)`: defaults to doing nothing
  7. It then calls `publishModules(publishKind, modules, deltaKinds, multiStatus)`: this basically walks the modules with the delta-kinds and calls `publishModule(publishKind, module, moduleDeltaKind)` for each.
      - the default implementation of `publishModule(publishKind, module, deltaKind)` mark that module's publishing state to _done_ (`PUBLISH_STATE_NONE`)
  7. It finally calls `publishFinish()`
      - We override to walk through the module list and, providing they're all published (`PUBLISH_STATE_NONE`), then we set the overall server publish-state to `PUBLISH_STATE_NONE` to indicate no further publishing required.

**Comment by briandealwis** [comment]
I *suspect* this setup evolved with the following in mind:

  1. publishing-tasks: publish projects to properly exploded WARs
  2. publisher-delegates: create a server config
  3. `publishModules()`: push up the exploded wars to the remote server

Because we're local, we skip steps 2 and 3.

**Comment by briandealwis** [comment]
The approach that I was going to push up modified our `LocalAppEnginePublishTaskDelegate` to add a new publish operation that stops the server if any module was marked to be removed.  But started to I wonder if we should restart the server, which caused me to question this approach.

My thoughts now are to:
  1. Modify the `LocalAppEnginePublishTaskDelegate` to check the server state and if running then only create `LocalAppEnginePublishOperation`s for `CHANGED` modules, and mark the server as requiring a restart.  So any changed files will be pushed up, but adding new modules and removing modules will require restarting the server.
  2. Change `publishFinish()` to stop the server if there are no published modules.
