### ISSUE TITLE
Autosave before run does not recompile

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1832]
1. Edit the servlet. Don't save.
2. Run As > App Engine
3. Say yes when prompted to save
4. What runs is the pre-save code, not the post-save code.

**Comment by briandealwis** [comment]
The problem here is that we save but then continue to launch such that the server ends up in a 'republish' state.  When the changed class files are republished, we still don't pick them up as we use `setAutomaticRestart(false)` and so the server doesn't detect/pick up these class changes.

**Comment by chanseokoh** [comment]
Yeah, it's very much like we change the source code while the server is running. If we do prompt, we will have to block the launch until any build gets completed. I think another option could be to show an error message if there is any open dirty editor on the files in the projects that the server has its modules, preventing launching altogether.

**Comment by briandealwis** [comment]
The `org.eclipse.wst.server.core.serverTypes/server` extension point also has a `synchronousStart` attribute — which we aren't setting — that is described as:

> **synchronousStart** - boolean value "true" or "false" to specify whether the server needs to be started synchronously. If "true", the server will execute publish and start jobs serially.

Though setting that doesn't appear to have solved the problem from what I see.

**Comment by briandealwis** [comment]
I don't have any good news to report.

Ultimately there is a race condition: the  [*save-action* in `StartAction`](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.ui/serverui/org/eclipse/wst/server/ui/internal/view/servers/StartAction.java?h=master#n157) doesn't wait for the results of the save to be processed by the workspace and instead barrels along to launch the server, even as the workspace's auto-build continues in parallel.  Although the files are eventually compiled, and the resource changes [are eventually noticed by `ResourceManager`](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/ResourceManager.java?h=master#n1093) such that the affected web module is marked as needing to be republished.  But that often happens long after the devappserver has been launched.

There is some support in the Platform/Debug launch framework to wait for a build, but this is [deliberately disabled by WTP](http://git.eclipse.org/c/servertools/webtools.servertools.git/tree/plugins/org.eclipse.wst.server.core/servercore/org/eclipse/wst/server/core/internal/Server.java?h=master#n3566) with a comment that is causes lockups.

I tried forcing a workspace compile in `LocalAppEngineServerBehaviour.publishStart()` but if the resource change events haven't been received then the newly-compiled classes may still be missed.  We can't `join()` on the auto build job as it leads to deadlock (I'm not sure why though).

It sounds somewhat similar to [this Eclipse WTP bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=337176).

**Comment by chanseokoh** [comment]
> I think another option could be to show an error message if there is any open dirty editor on the files in the projects that the server has its modules, preventing launching altogether.

I wonder if this would be an easier solution.

Or, we state promininantly in the save-prompt dialog (if it is possible) that the server may not pick up the saved contents as it will start running before a build completes.

**Comment by briandealwis** [comment]
I wish I had been more explicit in my previous writeup.  I've been digging into this further to see if I an come up with a way to either work around it or to fix it in WTP.  There are a lot of moving pieces, and 4 different cases to consider, and I don't think we'll be able to address all of them.

--- 

WTP Servers have two parts:
  1. There is the `IServer`/`Server` class.  This class provides the programmatic API for `start()`ing and `stop()`ing a server, and is responsible for performing publishing before or after the server is started.  It works with a `ServerDelegate` class.  The `Server`/`ServerDelegate` can be thought of managing the persisted configuration state. 
  2. There is the Platform/Debug `ILaunchConfigurationDelegate` that is responsible for executing or launching the actual server process.  It works with a `ServerBehaviour`.  These classes are responsible for launching actual server runtime instance.

## Server: Resource Changes

The `Server` class monitors for resource changes within a project (via a `org.eclipse.core.resources.ResourceChangeListener`), and manages the publishing state for the server.  When a resource change comes in, it schedules a separate `ResourceChangeJob` with the `o.e.core.resources.ResourceDelta` for *each* module in the server; these jobs are configured to run serially.  These `ResourceChangeJob`s walk the delta to mark the modules/projects that have changed and require re-publishing.  `ResourceChangeJob` is a `SERVER_FAMILY_JOB`.  Some time can pass between a resource change (e.g., saving a file, triggering an auto-build) and the publishing state being changed.

It is important that publishing should not happen if there is a `ResourceChangeJob` pending: the `ResourceChangeJob` has no way to know that the publishing state may have changed beneath it.  I'm not convinced that calling a `publish()` with a pending `ResourceChangeJob` will have the proper updates.

## Server Start

Calling `Server#start()` actually creates a `StartJob` which finds the appropriate launch configuration and then launches it:
```
Thread [Worker-15] (Suspended)	
	LocalAppEngineServerLaunchConfigurationDelegate(LaunchConfigurationDelegate).finalLaunchCheck(ILaunchConfiguration, String, IProgressMonitor) line: 179	
	LaunchConfiguration.launch(String, IProgressMonitor, boolean, boolean) line: 868	
	LaunchConfiguration.launch(String, IProgressMonitor, boolean) line: 739	
	LaunchConfiguration.launch(String, IProgressMonitor) line: 731	
	Server.startImpl2(String, IProgressMonitor) line: 3635	
	Server.startImpl(String, IProgressMonitor) line: 3571	
	Server$StartJob.run(IProgressMonitor) line: 416	
	Worker.run() line: 55	
```

If configured (and we do configure this), `Server#start()` will publish any pending changes (via a `PublishJob`) before triggering the `StartJob`.

This `StartJob` is also a `SERVER_FAMILY_JOB`.  Like `ResourceChangeJob`, it also locks the `Server` instance, and so attempting to `join()` with a `ResourceChangeJob` from within a `StartJob` results in deadlock.

## Launching

There are 4 ways to launch a server: 
  1. Via the _Servers_ view by selecting _Run_ or _Debug_ for a server.  Under the hood, this calls `StartAction#perform()`, which (1) prompts to save any dirty editors and (2) then calls `Server#start()`.
  2. Via a project or resource's _Debug As… > App Engine_.  Under the hood, this calls our launch shortcut `LocalAppEngineStandardLaunchShortcut`, which calls into our `LaunchHelper` which then calls `Server#start()`.
  3. Via out GCP Menu's _(Run|Debug) on App Engine_, which calls into our LaunchAppEngineStandardHandler.  This calls into our `LaunchHelper`, which then calls `Server#start()`.
  4. Through an existing launch configuration: e.g., _Run > {Run|Debug} Configurations…_ and then select and start a launch configuration.  This calls the launch configuration directly: the `Server#start()` is never called, and the  `StartJob` / `PublishJob` is never invoked.

## Complications

Normally the `ILaunchConfigurationDelegate`'s pre-launch checks prompt the user if there are relevant dirty files, and also build the associated projects if so configured.   This **is** done when launching using Approach 4 (_Run > Run/Debug Configurations…_).  But this **doesn't happen** with Approaches 1–3 as `Server#start()` disables the `ILaunchConfigurationDelegate`'s prompting to save any dirty editors, and it configures the `ILaunchConfigurationDelegate` to not build any associated projects.

But even supposing the `ILaunchConfigurationDelegate` can be configured to save-dirty-editors and build-dirty-projects, it would happen too late as the publishing step has already happened.  We need to re-publish, but ensuring that it occurs *after* the `ResourceChangeJob` has run as otherwise the publishing states can get out of whack.

We could perform a `join()` on the `ResourceChangeJob` instances.  However both `StartJob` and `ResourceChangeJob` lock the `Server` instance, such that attempting to `join()` on the `ResourceChangeJob` from our `ILaunchConfigurationDelegate` will cause deadlock if the `ILaunchConfigurationDelegate` will be executing within the `StartJob`.  So this can be done for Approach 4, but must be guarded for Approaches 1–3.

For Approaches 1–3, what we need to happen is:
  1. prompt and save any dirty editors,
  2. perform a rebuild to pick up these changes,
  3. `join()` the `ResourceChangeJob`s ensure the change deltas are processed and the the server publishing state is updated,
  4. then call `Server#start()` to publish the changes and start the server

This can be done for Approach 2 and 3.  Unfortunately I can't see a way to intercept the start action in Approach 1, unless we incorporate something like AOP.
