### ISSUE TITLE
App Engine Standard Runtime runtime

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1939]
"A good starting point for working with App Engine Standard Runtime runtime. Additional facets can later be installed to add new functionality to the project."

![image](https://cloud.githubusercontent.com/assets/1005544/26016391/cf8ec84a-3732-11e7-8a62-866fe9768bfc.png)

**Comment by briandealwis** [comment]
Those _Configurations_ are configured using _facet presets_ (`org.eclipse.wst.common.project.facet.core.presets`), and it's pretty easy to add presets for AES v7, v8, and AEF.

<img width="626" alt="screen shot 2017-07-21 at 3 03 29 pm" src="https://user-images.githubusercontent.com/202851/28478311-de7c0ece-6e25-11e7-9e24-a9824ccfe8f5.PNG">

There's a minor issue in our runtime definition in that we share a single runtime definition for both the AES Java 7 and Java 8.  The problem manifests once we have created an AES project (and thus create an _App Engine Standard Runtime_ `IRuntime`) as subsequent attempts to  use _New > Dynamic Web Project_ show a wizard with a _Dynamic web module version 3.1_ and _Default Configuration for App Engine Standard Runtime_ configuration selected.  Once the user enters a project name, they see an error (below).  I suspect the framework has selected AESv7, Java 1.8, and DWP 3.1 as these are the default versions of the facets associated with the runtime component. The default version of a facet can be explicitly defined (as we do for AES, which is v7), or otherwise the framework selects the highest version (hence Java 1.8 and 3.1).  So we end up with this situation where the versions chosen are in conflict.  Although the user can either change the configuration, or change the _Dynamic web module version_ to 2.5, it's puzzling.  Raised #2188 to track this.

<img width="581" alt="screen shot 2017-07-21 at 3 12 07 pm" src="https://user-images.githubusercontent.com/202851/28479199-5c3727d8-6e29-11e7-8c46-da5eca133164.PNG">

**Comment by chanseokoh** [comment]
> The default version of a facet can be explicitly defined (as we do for AES, which is v7), or otherwise the framework selects the highest version (hence Java 1.8 and 3.1).

Then, is it possible to set Java 1.7 and and Servlet 2.5 as default values of our runtime?

**Comment by briandealwis** [comment]
Unfortunately not with the current single App Engine runtime definition.  If we split our runtime definition into 2 definitions, one for AES-7 and the other for AES-8, then yes it should just work.
