### ISSUE TITLE
Deployment errors

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1998]
There are several problems here:

![image](https://cloud.githubusercontent.com/assets/1005544/26724783/324dd642-4769-11e7-9183-d2c2cb8403bf.png)

1. The error should appear in red text in the title area below Deployment parameters for "fred". Not in a separate label.
2. The Deploy button should be disabled in this case.
3. I suspect in this case we shouldn't even be showing this project in the list.

**Comment by elharo** [comment]
related to #1417

**Comment by chanseokoh** [comment]
> 1. The error should appear in red text in the title area below Deployment parameters for "fred". Not in a separate label.

The reason is probably that we can't embed a hyperlink in the title area. We have another error message (there are two in total) related to checking if a project has an App Engine application. 
![selection_004](https://cloud.githubusercontent.com/assets/10523105/26735769/53d82bd2-4791-11e7-9e1f-dbfb123209be.png)


> 2. The Deploy button should be disabled in this case.

I think it was intentional, just letting gcloud validate and fail if a user really wanted to force-test it. @patflynn seems to prefer this option in general.

> 3. I suspect in this case we shouldn't even be showing this project in the list.

Probably there is no single-call API that checks if each in the entire list of projects has an App Engine application. To filter projects that don't have an AE application, we would need to make individual API calls, which will take too much time. So, the current way is to check an application when a user select a particular project.

Moreover, the above error is also about insufficient permission. I think it is less confusing to not filter out such projects, as users who are not aware if they don't have permission may wonder why their projects are not shown.

**Comment by diego92sigma6** [comment]
Closing as not planned. Please reopen if needed
