### ISSUE TITLE
Our own XSD manual validation on appengine-web.xml doesn't seem necessary

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2074]
While tackling #1801, I noticed that skipping the `xsdValidation()` call in `XmlValidator.validate()` still puts error problem markers if `appengine-web.xml` does not confirm to the XSD we supply. I think this is supported natively by the Eclipse XML validation framework, as we register the XSD through an extension:

```xml
  <extension point="org.eclipse.wst.xml.core.catalogContributions">
    <catalogContribution>
      <uri
          name="http://appengine.google.com/ns/1.0"
          uri="xsd/appengine-web.xsd"/>
    </catalogContribution>
  </extension>
```

**Comment by briandealwis** [comment]
Makes sense.

**Comment by briandealwis** [comment]
Perhaps we should move the local copies of the JEE XSDs (#2066) into `.validation` too?

**Comment by chanseokoh** [comment]
> Perhaps we should move the local copies of the JEE XSDs (#2066) into .validation too?

You mean `.validation.test`? You know those JEE XSDs are just for eliminating the flaky test as an absolute solution.

**Comment by briandealwis** [comment]
The reason we're getting `appengine-web.xml` validation is because [we contribute an XSD for that namespace](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.validation/plugin.xml#L237).  I _believe_ the flakey tests had `schemaLocations`, and so the tests were trying to retrieve the XSDs remotely and timing out.

I'll file an issue to track this.
