### ISSUE TITLE
Category version in install binary has ".qualifier"

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2211]
We always had the `.qualifier` part in our code, so this seems to be a post-effect of #2043.

![selection_031](https://user-images.githubusercontent.com/10523105/28839650-51a6f072-76c2-11e7-82f1-349a485dc99a.png)

![selection_032](https://user-images.githubusercontent.com/10523105/28839657-54834ea8-76c2-11e7-9877-59ae23042233.png)

**Comment by briandealwis** [comment]
Ah it's because of our [post-signing product re-publishing step](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/wiki/Release-Details#steps-covered-by-releaserelease_after_kokorosh):
> 6. Run the Eclipse p2 Product Publisher to add our custom p2 metadata to the repository.

which manually invokes the p2 _product publisher_  and thus doesn't benefit from the _.qualifier_ expansion performed by Tycho.

Given that this is a release version, and the category IU is never actually downloaded to the user (and thus doesn't need to be unique), we should just update the [release instructions](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/wiki/Cloud-Tools-for-Eclipse-Release-Instructions) to drop the _.qualifier` when updating the .product version.

This issue can go away whenever we're able to do signing as part of the build process.

**Comment by briandealwis** [comment]
Updated release doc.
