### ISSUE TITLE
the project field in the dataflow wizard should use the project selector used for app engine

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2217]
![image](https://user-images.githubusercontent.com/1005544/28852329-45e02f86-76f6-11e7-8bb0-a1e75d1ccf8b.png)

**Comment by briandealwis** [comment]
The problem here is that the same component (`RunOptionsDefaultsComponent`) is used in a few places, including the project's _Dataflow_ property page, and the _Dataflow Pipeline_ launch configurations.  The _Dataflow Pipeline_ page doesn't have enough room for the project selector, at least not as it is currently.

<img width="682" alt="screen shot 2017-08-02 at 3 48 02 pm" src="https://user-images.githubusercontent.com/202851/28891943-37ef4282-779a-11e7-83b3-5aed9f4dfbed.PNG">

**Comment by elharo** [comment]
We might need to use different components in different places then. The general UI principle in play here is that see and choose is easier than remember and type.
