### ISSUE TITLE
FlexDeployCommandHandler throws wrong exception

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2391]
`IllegalStateException` is incorrect here. This should be a checked exception, possibly a `CoreException`, since it comes from a problem outside the code. 

```
  @Override
  protected StagingDelegate getStagingDelegate(IProject project) {
    String appYamlPath = new FlexDeployPreferences(project).getAppYamlPath();
    IFile appYaml = project.getFile(appYamlPath);
    if (!appYaml.exists()) {
      throw new IllegalStateException("Invalid app.yaml path from project preferences.");
    }
    IPath appEngineDirectory = appYaml.getParent().getLocation();
    return new FlexStagingDelegate(appEngineDirectory);
  }
```

**Comment by chanseokoh** [comment]
That is true. From the perspective of this code, that is certainly true.

The reason it is a runtime exception is that this code assumes it must exist, which is true because the deploy dialog disables the deploy button until users specify an existing `app.yaml`. So, after that and at this point, `app.yaml` should exist and this code is assuming that.

However, I am open to change it, as what you said is true from another perspective.

**Comment by chanseokoh** [comment]
So, it is quite like `Preconditions.checkState(app.yaml exists)` currently.

**Comment by elharo** [comment]
app.yaml is an external file. Just because we checked it previously doesn't mean it hasn't been deleted or moved in the meantime. This should be a checked exception.
