### ISSUE TITLE
CSR Login integration

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2392]
Cloud Source Repositories should mostly work out of the box with Eclipse git support. However authentication is problematic because CSR doesn't use standard Git authentication. See https://cloud.google.com/source-repositories/docs/adding-repositories-as-remotes for the extra steps.

I'm not sure what the chance is we can fix CSR to not require this or fix Eclipse Git to support the necessary authentication, but we can probably add our own context menu to do the non-standard initial steps. (adding a repository as a remote, cloning a repository)

**Comment by elharo** [comment]
Even once the repo is authed and created from the command line pushing from inside Eclipse fails:

![image](https://user-images.githubusercontent.com/1005544/30487988-0d055b84-9a03-11e7-9625-e356c26804d1.png)

**Comment by etanshaul** [comment]
with intellij we spent some time looking into auth pain points. may have some overlapping info here:

https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1174

**Comment by elharo** [comment]
Eclipse bug explaining JGit doesn't support credential helper: https://bugs.eclipse.org/bugs/show_bug.cgi?id=441198

**Comment by elharo** [comment]
FYI relevant sections of .git/config

```
[user]
        name = Elliotte Rusty Harold
        email = elharo@nospem.org
[credential]
        helper = gcloud.sh
[remote "google2"]
        url = https://source.developers.google.com/p/savvy-climber-152000/r/registrarrepo
```

**Comment by briandealwis** [comment]
Other details:
  - [The `git-credential` man page](https://www.kernel.org/pub/software/scm/git/docs/git-credential.html)
  - [The underlying API](https://www.kernel.org/pub/software/scm/git/docs/technical/api-credentials.html)
  - [GCP instructions for adding a remote repo](https://cloud.google.com/source-repositories/docs/adding-repositories-as-remotes)

EGit uses a single credentials provider, `EgitCredentialsProvider`, to handle obtaining credentials; it pulls credentials from the Eclipse secure storage.  It looks like we'd need to make it examine the `.gitconfig`.

**Comment by elharo** [comment]
If that works, this would be a huge win. I would love to have this functionality. It would open up so much more of the GCP workflow to Eclipse.

**Comment by briandealwis** [comment]
Just tried this out and I was able to push to a new repository with my account email as the _user_ and the result of `gcloud auth print-access-token` as the _password_.

**Comment by chanseokoh** [comment]
`gcloud auth print-access-token` prints the OAuth2 access token of the account logged in with `gcloud auth login`.

`gcloud auth application-default print-access-token` prints the access token of the current Application Default Credential. gcloud allows the user to temporarily set their OAuth2 user credential as ADC with `gcloud auth application-default login`. In this case, `gcloud auth application-default print-access-token` will print the OAuth2 access token logged in with this `gcloud auth application-default login`, which means `gcloud auth print-access-token` and `gcloud auth application-default print-access-token` may print different tokens. They are basically independent.

Remember I said `gcloud auth application-default print-access-token` prints the access token of the current ADC. So, for example, this command can be used to print an access token from an arbitrary credential, including service account keys. In the example below, `gcloud auth application-default print-access-token` doesn't work by default because I've never logged in with `gcloud auth application-default login`, but by defining `GOOGLE_APPLICATION_CREDENTIALS`, it will 

```
$ gcloud auth application-default print-access-token 
ERROR: (gcloud.auth.application-default.print-access-token) The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

$ GOOGLE_APPLICATION_CREDENTIALS=~/tmp/service-account-my-test-key.json \
  gcloud auth application-default print-access-token 
<... prints the access token of the JSON key...>
```

**Comment by briandealwis** [comment]
So we have a similar problem in that we don't have a default account in CT4E (akin to the ADC).  I updated [my comment above](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2392#issuecomment-393216981) to include the input/output provided to the Cloud SDK's credential helper (`git-credential-gcloud.sh`), and given that the full repo location isn't provided, it must only be providing the current login account. 

EGit's [current remote repository UI](https://wiki.eclipse.org/EGit/User_Guide#Cloning_Remote_Repositories) is very GIT-URI centric (i.e., `https://xxx@yyy/path/to/repo`).  I think we'll need to augment or sidestep the existing EGit workflows to provide a way to choose the right account.  We could work with EGit and make that first _Source Git Repository_ page host a tabbed-folder with additional tabs for custom providers "Clone" (current content for a URI), "Google Cloud", "Github", …

EGit also has some support for spawning a remote clone operation by dragging a Github URL onto an Eclipse window.  We could hook into that too, so that dragging `https://console.cloud.google.com/code/develop/browse/REPO?project=PROJECT` will do the right thing.

**Comment by elharo** [comment]
`gcloud auth print-access-token` is not documented, and we need to be very cautious before depending on this. I'm going to try to discuss this with some of the internal teams, and see if we can get some commitment to this first.

One question we need and answer to is whether using the OAuth token as a password is a documented and committed means of access to CSR. This is  separate question from whether we can rely on `gcloud auth print-access-token` giving us that access token.

**Comment by elharo** [comment]
Look at the bottom of this page:

https://cloud.google.com/source-repositories/docs/adding-repositories-as-remotes

That is, the section on "Generating static credentials"

This might give us another path into solving this problem.

**Comment by briandealwis** [comment]
JGit does not currently support `.gitcookies` either ([feature request](https://bugs.eclipse.org/bugs/show_bug.cgi?id=494643)).

**Comment by chanseokoh** [comment]
> One question we need to answer first is whether using the OAuth token as a password is a documented and committed means of access to CSR.

I couldn't find such a doc, but [`git-credential-gcloud.sh` in the Cloud SDK (a Git credential helper for Google CSR)](https://cloud.google.com/source-repositories/docs/adding-repositories-as-remotes#adding_the_repository_as_a_remote) has been passing an access token as a password. I don't think CSR will change the design to use it as a password.

```
$ git-credential-gcloud.sh get <<EOL
protocol=https
host=source.developers.google.com
EOL
username=user@example.com
password=<... some access token ...>
```

**Comment by elharo** [comment]
Do we need .gitcookies for CSR?

**Comment by briandealwis** [comment]
The process for generating `.gitcookies` seems pretty icky.  The auth-token is much easier for us to perform.

**Comment by chanseokoh** [comment]
> Do we need .gitcookies for CSR?

No, unless the user decided not to use the Cloud SDK and opted for https://cloud.google.com/source-repositories/docs/adding-repositories-as-remotes#generating_static_credentials (the link from your comment). But this alternative to use `.gitcookies` seems more complicated to set up manually than the access-token-as-a-password.

**Comment by chanseokoh** [comment]
Details about some access token, including expiration time, can be queried by
````
curl https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=<access token>
````
Entering access tokens from gcloud shows that they expire after an hour.

**Comment by briandealwis** [comment]
Our access tokens from `ide-login` have the same expiry.

**Comment by chanseokoh** [comment]
For `gcloud auth application-default print-access-token`, I confirm `GOOGLE_APPLICATION_CREDENTIALS` takes precedence over the login credential set by `gcloud auth application-default login`. So, to be completely free of any potential pitfalls, the user needs to ensure the variable is not set.

Linux: `GOOGLE_APPLICATION_CREDENTIALS= gcloud auth application-default print-access-token`
Windows: `cmd /C "set GOOGLE_APPLICATION_CREDENTIALS= && gcloud auth application-default print-access-token"`

**Comment by cperez1000** [comment]
I'm using Spring Cloud Config which relies on JGIT... But I can't connect to repo in GCP. And I don't know if that's even possible as I don't know if JGIT supports that. Can you please help me confirm?

**Comment by briandealwis** [comment]
Hi @cperez1000.  I'm not familiar with Spring Cloud Config, but JGit does not *yet* support gitcookies though it looks [like an implementation is close to landing](https://git.eclipse.org/r/#/c/132704/).

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
