### ISSUE TITLE
Don't show appengine runtimes/servers for non-appengine projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#254]
That is, projects that don't contain either appengine-web.xml or app.yaml

Maybe with facets?

**Comment by branflake2267** [comment]
This would be a good idea, otherwise you can add a project that doesn't. And you get an error that is obvious. 

This is what happens if you start with out the `appengine-web.xml`
![screen shot 2016-11-04 at 3 24 38 pm](https://cloud.githubusercontent.com/assets/1326504/20024377/775d7f82-a2a3-11e6-8524-43d720641ac2.png)

**Comment by chanseokoh** [comment]
The issue seems to say App Engine projects can be run only on the App Engine runtime. If that's the case, then it's in conflict with #930, which says we allow any runtime to run App Engine projects.

BTW, I think what @branflake2267 said above is saying a different one: the App Engine server running non-App Engine projects.

**Comment by chanseokoh** [comment]
The title IMO is confusing, and I believe I misunderstood this issue previously. Correct me if I'm wrong, but I've changed the title from

"Only show appengine runtimes/servers for appengine projects"

to

"Don't show appengine runtimes/servers for non-appengine projects."

**Comment by chanseokoh** [comment]
So, what we did instead of hiding App Engine runtimes/servers was to prevent adding non-appengine projects to App Engine servers: #928

Perhaps this was the best we could do. I believe @akerekes couldn't find a way to make WTP hide our servers. Actually, I like the solution of #928: I think it's better to explicitly show the reason that you cannot use the App Engine server, rather than silently hiding the servers. Hiding might confuse users.
