### ISSUE TITLE
JDK Staging error: unable to stage app

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/google-cloud-eclipse#2548]
See https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1316#issuecomment-341140332

Eclipse doesn't seem to be setting the project configured JDK for staging, causing the error:

`Unable to stage app: Cannot get the System Java Compiler. Please use a JDK, not a JRE`

**Comment by chanseokoh** [comment]
This should have been fixed. Let's talk offline.

**Comment by chanseokoh** [comment]
@jonathanlal the latest Eclipse plugin version is supposed to use the JDK configured for your project (fixed in #2195). Can you confirm you are running 1.4.1? If not, please do _Help_ > _Check for Updates_. It won't matter which JDK you use to run your Eclipse anymore, so no need or point of dealing with `eclipse.ini`. Use whatever JDK you need or want to run your Eclipse, and just set a correct JDK in your project.

If this still doesn't work, we need to look into what's actually happening.

**Comment by jonathanlal** [comment]
@chanseokoh 

I am using Eclipse Jee Mars.2 (4.5.2)
"Google Cloud Platform for Eclipse 4.5 and later" **version is: 1.3.1.201709121426**
I had jdk8 set as my system environment, and also for the eclipse .ini file. 
The project was using java 7.  It was working fine from July up until i let Java automatically update itself on my computer to a newer version of java 8. 

Have since fixed the issue by removing all the java versions on my system and downloading only java 7.

**Comment by chanseokoh** [comment]
If you expand the "JRE System Library" container in your project, you'll see the JDK directory it uses.

![selection_032](https://user-images.githubusercontent.com/10523105/32288985-e1647086-bf0b-11e7-9dd4-56d439bc6fee.png)

In my case above, the root JDK directory is `.../jdk8-google-v7-64/`. If you do `.../jdk8-google-v7-64/bin/java -version`, does it say it is a JDK? If so, we need to look into it further.

**Comment by patflynn** [comment]
It looks like @jonathanlal isn't on 1.4.1. is the fix included in 1.3.1?

**Comment by chanseokoh** [comment]
Yeah, fixed in 1.3.1, which was released on Sep 13.

**Comment by jonathanlal** [comment]
@chanseokoh 

As i mentioned i've since reverted back to using only jdk7. So not sure if your questions are still applicable to the bug/problem i was encountering. But if needed i can try the configuration i was using yesterday when this happened (jdk8 system/eclipse with a jdk7 project) and get back to you with that info.

Here is the information nevertheless...

![image](https://user-images.githubusercontent.com/13243000/32289505-d3bc3982-bf2e-11e7-99f3-03d6fdcb97b6.png)

![image](https://user-images.githubusercontent.com/13243000/32289718-6bd950d8-bf2f-11e7-9d66-53293571a1a1.png)

**Comment by chanseokoh** [comment]
If you are interested in digging into the problem, you could try going back to the yesterday's environment (where you have Java 8).

Also, I just realized that `java -version` can't tell you if it's JDK or not. I think the presence of `<JDK root>/bin/javac` (compiler), `.../bin/jar`, and `../bin/jarsigner` and such will tell you if it's JDK or not.

BTW, I positively verified that deploy picks up the JDK that I configure in 1.4.1. If I set a JRE, I get the error, and if I set a JDK, I don't get the error.

**Comment by briandealwis** [comment]
The directory name (in the prompt in @jonathanlal's command shell window) would indicate that it's a JDK. 

CT4E use JDT's launching facilities to find the JRE/JDK configured for the project.  There are two ways to configure a JRE or JDK for a project. The project can specify an _execution environment_, or the project can specify a particular JRE/JDK.

By default, new App Engine standard are set up to use the `JavaSE-1.7` or `JavaSE-1.8` execution environments. JDT maintains set of mappings of execution environments to a corresponding JRE or JDK.  The list of configured JRE/JDKs is maintained in _Preferences > Java > Installed JREs_, and the execution environment mappings is in found in _Preferences > Java > Installed JREs > Execution Environments_.  It's worth reviewing both pages as it's possible that your Java update has caused a change to the `JavaSE-1.7` execution environment (e.g., since the old JDK was removed, it may have chosen some other JRE/JDK instead).

You can change your project's configuration, to select either an execution environment or a particular JRE/JDK, by changing the project's JRE library. Right-click on the project and select _Properties > Java Build Path > Libraries_, then select the _JRE System Library_ entry and click the _Edit…_ button.  You'll see a dialog like the following:
<img width="671" alt="screen shot 2017-11-01 at 2 49 26 pm" src="https://user-images.githubusercontent.com/202851/32291608-eecd294a-bf13-11e7-8a85-1853e11b27d0.PNG">

You need to ensure that your project's selected option is pointing to a JDK.  My guess is that it's pointing to a JRE.

(This may be a good candidate for a FAQ @parkjam4)
