### ISSUE TITLE
Install Managed Cloud SDK on startup

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2750]
On start up, if Managed SDK is enabled  but not installed, then install

**Comment by chanseokoh** [comment]
I think this slightly overlaps with #2756 and #2757. (Sorry, my bad.) I'd like to separate install and update, because auto-update is really necessary for feature completeness, but auto-install on startup is somewhat optional.

We can also think about notifications later, but here's what I think.

> check if Cloud SDK was found and notify user if not

Not sure if we want a notification here. We'll auto-install anyway (in the background or eventually).

> if custom SDK found, check if up-to-date and notify user if not

An optional feature (and actually I did not intend to do so), so let's create a separate PR.

**Comment by briandealwis** [comment]
I wonder if we should log the output somewhere, in case the installation fails.  Or do we always open a console?
