### ISSUE TITLE
Revert SDK location to managed SDK location

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2800]
1. Open the preferences with the SDK set to a managed SDK. Notice that the location in gray text points to the managed SDK.
2. Switch to a local SDK. Select one.
3. The text now indicates a local SDK.
4. Switch back to a managed SDK by unchecking the check box.

The SDK location should now switch back to but it doesn't. It still points to the previously chosen local SDK.

![image](https://user-images.githubusercontent.com/1005544/36168899-a6cc8ada-10c8-11e8-995a-d39d175cec99.png)

(Ignore the SDK version field. That's something else I'm experimenting with in the branch where I noticed this.)

**Comment by briandealwis** [comment]
That text field normally reflects the setting of the `CLOUD_SDK_PATH` preference.  But if the CLOUD_SDK_PATH is unset then the text field will show its message hint (the text shown when there is no text — like the light grey `Quick Access` text in the _Quick Access_ box).  The confusion arises as the message hint is rendered in the same way as when the text box is not enabled.  We're setting the message hint is set to the initially discovered Cloud SDK location (the value of `new CloudSdk.Builder().build().sdkPath()`).  With our new initialization logic (#2761) when the Cloud SDK is not found in one of the normal places then we use the Managed Cloud SDK.

So when you first open the pref page, you don't have a `CLOUD_SDK_PATH` preference so you are in Managed Cloud SDK mode.  So the message hint is shown with location of the Managed Cloud SDK.

You then checked the _Use local SDK_ button and configure a location, setting the `CLOUD_SDK_PATH`.

You then unchecked the _Use local SDK_ button, which disables the text field, but the text field continues to show the `CLOUD_SDK_PATH` now greyed.

So I'll argue that the bug is not that the location value doesn't change back, but that the location value is set in to the Managed Cloud SDK location in the first place.  It made sense previously when we were either using the found location or an explicit location.

I think the answer is to just not set the message hint.
