### ISSUE TITLE
Installation problem with Docker Tooling on Neon

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2857]
I am installing a non-signed version built from HEAD just for testing. On Neon, I encountered the following problem.

![selection_001](https://user-images.githubusercontent.com/10523105/36707729-9581f862-1b3d-11e8-911a-d90e093c5498.png)

Looks like the installer-proposed solution is to modify the version of the Docker Tooling to be compatible.

![selection_004](https://user-images.githubusercontent.com/10523105/36707988-d4e92d12-1b3e-11e8-9861-6859e2706c5b.png)

The error message I see when I select _Show original error and build my own solution_ is
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Docker Tooling 3.2.0.201712060514 (org.eclipse.linuxtools.docker.feature.feature.group 3.2.0.201712060514)
  Missing requirement: Docker Core Plugin 3.2.0.201712060514 (org.eclipse.linuxtools.docker.core 3.2.0.201712060514) requires 'bundle com.spotify.docker.client 6.1.1' but it could not be found
  Cannot satisfy dependency:
    From: Docker Tooling 3.2.0.201712060514 (org.eclipse.linuxtools.docker.feature.feature.group 3.2.0.201712060514)
    To: org.eclipse.linuxtools.docker.core [3.2.0.201712060514]
```

**Comment by chanseokoh** [comment]
No problem on Oxygen, on the other hand.

**Comment by elharo** [comment]
We already serve different versions in the two environments. 

FYI, if we can't resolve this it would be acceptable to include this only on Oxygen. In that case, we should probably revert Neon to including the old Docker Editor as it did in 1.5.1.

**Comment by briandealwis** [comment]
Huh, you must have installed the Docker Tools prior to their committing the new Docker/JDT launcher.  Or else you have a Docker Tools update site that I wasn't able to fetch!  Could you look at your _Preferences > Install/Updates > Available Update Sites_ and look for anything prefixed with `http://download.eclipse.org/linuxtools`?

**Comment by briandealwis** [comment]
Hmm. We might have to revisit how we link to the Docker Tools.  We're pulling in Docker Tools via the [3rd party feature](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/features/com.google.cloud.tools.eclipse.3rdparty.feature/feature.xml#L27), which burns in the specific version found at build-time.  Since we're referencing different versions of Docker Tools for Neon and Oxygen, the version available from our `gcp-repo` will depend on the platform built for the release.

**Comment by chanseokoh** [comment]
I tried it on a fresh new Neon, unpacked from a zip.

**Comment by briandealwis** [comment]
@elharo we have an issue in that the version of the Docker Tools included in our `gcp-repo` depends on the `eclipse.target` used for the build.  Since our build targets Oxygen by default, we'll burn the Oxygen stream of Docker Tools, but it can't be installed on Neon.

Since we're not depending on any functionality from Docker Tools — and haven't yet verified that the Neon stream of Docker Tools still works with current Docker installs — @chanseokoh suggests that we restore the Docker Editor for 1.6.0.
