### ISSUE TITLE
When SDK is found in customary location, preferences don't show this 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2897]
![image](https://user-images.githubusercontent.com/1005544/37056557-c8db2934-2152-11e8-9dc7-1815d5c31d73.png)

- Cloud Tools for Eclipse version: 1.6.0.201803061547
- Google Cloud SDK version: 188.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Mac OS X 10.13.3
- Java version: 1.8.0_144

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

Screenshots and stacktraces are helpful.

**Comment by chanseokoh** [comment]
Kind of tricky to search for the customary locations technically. The search is done by appengine-plugins-core when doing `new CloudSdk.Builder().build().getSdkPath()` _and only if_ our `CloudSdkPreferenceResolver` does not intercept it. That is, if the currently persisted preference is to use the managed SDK, we can't go far into let appengine-plugins-core search an SDK. It'll just return the location of the managed SDK due to our resolver.

Of course, there will be ways to temporarily prevent our resolver from interfering, but I cannot think something other than ugly hacks.

**Comment by chanseokoh** [comment]
It may be better to change the appengine-plugins-core API to expose the SDK search method.

**Comment by chanseokoh** [comment]
Turns out we can already use `new PathResolver().getCloudSdkPath()` to search for an SDK.

**Comment by elharo** [comment]
Do we need to search for an SDK in this case? We already have one, and `CloudSdk.getVersion()` will tell us what we need to know.
