### ISSUE TITLE
Always update managed SDK on startup

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3054]
Rather than notify of an update being available (#3032), use the notification to allow the user to skip the update.

**Comment by elharo** [comment]
@etanshaul Check with IntelliJ team why some people always skip.

**Comment by etanshaul** [comment]
We noticed that some users (a small subset) continuously were skipping the initial cloud sdk install. Presumably this was due to the file-size / install time (perhaps made worse by a slow connection). So we added the feature to prevent subsequent install attempts after the initial install cancellation.

I don't think we did anything for the automatic updates though. @ivanporty ?

**Comment by ivanporty** [comment]
Correct, we definitely see some trend for certain type of users to intentionally cancel any attempts to install Managed SDK, one of the ideas is app-engine-java component install taking quite some time plus it doesn't provide any meaningful feedback during install.

As for updates, it seems opt-in users who did install Managed SDK update their installation with no issues so far, almost no cancellations.

**Comment by briandealwis** [comment]
Thanks for the info!

**Comment by briandealwis** [comment]
From the feedback on #3084, we're going to keep the opt-in update.  Filed #3140.
