### ISSUE TITLE
Unable to configure Google Cloud SDK on Windows/Eclipse IO: 2

### ISSUE THREAD

**Issue by pkotowski** [GoogleCloudPlatform/google-cloud-eclipse#3065]
Configuration:
- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 201.0.0
- Eclipse version: 4.7.3.v20180330-0640
- OS: Windows 10 10.0
- Java version: 1.8.0_73

ERROR: gcloud crashed (IOError): [Errno 2]

Registry key value to enable long filename already set and computer has been restarted before that error.

Details:
#============================================================#
#= Creating update staging area                             =#
#============================================================#
#= Installing: gRPC python library                          =#
#============================================================#
#= Installing: gRPC python library                          =#
#============================================================#
#= Installing: gcloud app Java Extensions                   =#
#============================================================#
ERROR: gcloud crashed (IOError): [Errno 2] No such file or directory: u'D:\\Windows\\Users\\MuuMee\\AppData\\Local\\google-cloud-tools-java\\managed-cloud-sdk\\LATEST\\google-cloud-sdk.staging\\platform\\google_appengine\\google\\appengine\\tools\\java\\jetty93\\jetty-distribution\\lib\\apache-jstl\\org.apache.taglibs.taglibs-standard-spec-1.2.5.jar'

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics

**Comment by briandealwis** [comment]
It seems you've hit the [dreaded `MAX_PATH` problem on Windows](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/595): that path is 259 characters, plus the trailing NUL byte makes it 260 characters.  Our next release will put this auto-installed Cloud SDK in a different location that should reduce the change of hitting this path-length limit.

There are two workarounds.

   1. Microsoft have a [documented method for enabling long pathnames](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath) requiring a small change to the Windows registry (search for `HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled`).  We're not sure if there is any negative consequence in making this change.

   2. You can manually install the Google Cloud SDK in a different location (e.g., `D:\SDK`) so that you won't hit the `MAX_PATH` limit.  Then configure Cloud Tools for Eclipse to use this location in _Preferences > Google Cloud Tools > Google Cloud SDK Location > Choose SDK_.

**Comment by elharo** [comment]
We should ask the Cloud SDK team to detect and report this case. A user could hit it without installing Eclipse.

**Comment by elharo** [comment]
b/80242158
