### ISSUE TITLE
Kokoro configs comments

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3152]
Noticed our kokoro configs have this comment:

```
#
# This is just an initial version based on the Travis build script, the build
# needs UI, which haven't been tested, just copied over from .travis.yml
#
```

This can probably be deleted now.

**Comment by chanseokoh** [comment]
The file is `kokoro/ubuntu/continuous.sh`, which we haven't set up and isn't being used. The merge CI we currently use is on Windows only. I learned it the hard way that enabling UI on Kokoro Ubuntu needs a special setup (see [here](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.7.0D/kokoro/ubuntu/new_release.sh#L31)), so that might be the reason that no Ubuntu CI has ever been set up and the comment.

**Comment by elharo** [comment]
If we're not using it, let's get rid of it then.
