### ISSUE TITLE
gcloud app deploy --verbocity=debug

### ISSUE THREAD

**Issue by iatomic** [GoogleCloudPlatform/google-cloud-eclipse#3273]
We are deploying from a directory containing: 
ROOT.war
#Dockerfile below
FROM tomcat:8.5-jre8-alpine
RUN rm -rf /usr/local/tomcat/webapps/ROOT
ADD ./ROOT.war /usr/local/tomcat/webapps/ROOT.war
RUN /usr/local/tomcat/bin/catalina.sh run && chown -R tomcat:tomcat /usr/local/tomcat/

#app.yaml below
runtime: custom
env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud-gcp"

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
manual_scaling: 
  instances: 1

resources:
  cpu: 1
  memory_gb: 3

=============================
our tomcat starts fine...

We are waiting for hours viewing gcloud output: 
DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
DEBUG: Operation [operations/build/tytus-220022/ODhiN2YzNGYtNjk1OS00NGI5LWJkNTItODljNjM2YzRlOGM3] not complete. Waiting 1s.
DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
DEBUG: Operation [operations/build/tytus-220022/ODhiN2YzNGYtNjk1OS00NGI5LWJkNTItODljNjM2YzRlOGM3] not complete. Waiting 1s.
DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
DEBUG: Operation [operations/build/tytus-220022/ODhiN2YzNGYtNjk1OS00NGI5LWJkNTItODljNjM2YzRlOGM3] not complete. Waiting 1s.
DEBUG: Reading GCS logfile: 416 (no new content; keep polling)
DEBUG: Operation [operations/build/tytus-220022/ODhiN2YzNGYtNjk1OS00NGI5LWJkNTItODljNjM2YzRlOGM3] not complete. Waiting

Failure status: UNKNOWN: Error Response: [4] DEADLINE_EXCEEDED...

then we land up with no app deployed anyplace... I frankly do not get the use of gcloud app deploy...
why not have Dockerfile and deploy like it is at openshift...
or like with google Kubernetes we do

kubectl run --image=gcr.io/xxxxxx and and image would start......
...

**Comment by chanseokoh** [comment]
Hi,

Your image just won't build. Docker build hangs because you are launching Tomcat. You first need to remove `/usr/local/tomcat/bin/catalina.sh run`. If you do `docker build .` locally, it'll hang.

But even if you remove the command to run Tomcat, your image still won't build, because your image doesn't have the `tomcat` user and group. `chown` will fail. You'll have to add the user and the group first.

From previous interactions, I am thinking perhaps you need to learn a little bit more about building Docker images. I suggest you to get some help from someone who is knowledgeable with Docker.

And you certainly need to build and test your image locally before trying to deploy to anywhere.

Lastly, this is the CT4E Eclipse plugin repo, so I suggest you to use to proper channels for this kind of question.

**Comment by iatomic** [comment]
We built all and all is running.... I think we know a lot about docker images. Asking questions if not a sign of ignorace. 
I am not sure you understood what we were asking a few times.

>From previous interactions, I am thinking perhaps you need to learn a little bit more about building Docker images. I suggest you to get some help from someone >who is knowledgeable with Docker.

I think you are badly mistaken in this comment you are making above. We got all running fine. 
The eclipse tools for the cloud are not up to the standards I am used to. I am a former Borland guy. 
when we built tools for develpers. google was still in a garage. Dumping comments onto customers that they we need to learn a little bit is not really
the right way to go about things. Maybe the products google builds need to be better built?

**Comment by chanseokoh** [comment]
Sorry if you felt my comment was bad. I did not mean it.

I just realized the Dockerfile you described does not built, since there were two issues: you are running Tomcat as part of the build, and your `chown` fails. The Dockerfile does not build, so it just seemed obvious you did not try building it locally or don't really understand how you should build an image with Dockerfile.

**Comment by iatomic** [comment]
We got all running. Those insane run-arounds are PURELY because of google cloid ABSOLUTELY poorly built and POORLY  designed tools. The toold you have are PRIMITIVE and what is worst in their primitive design they cannot even be called robust this is truly pathetic engineering approach from google. That being said we got all running. FYI on openshift, with Docker images we were running in 1 hr. On gogle cloud...we wasted like a week... your tools for gcloud ....
