### ISSUE TITLE
ProjectUtils.waitUntilNoBuildErrors(project); times out

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3567]
We got blocked for over a week because  ProjectUtils.waitUntilNoBuildErrors(project) doesn't fail sensibly and times out, which leads to undiagnosable, incomprehensible stack traces in the log.

This method shouldn't wait more than the resonable number of seconds to build. Then, rather than timing out, it should fail (`Assert.fail`) with an error that indicates the build errors found in the project.

**Comment by chanseokoh** [comment]
That is weird. The code is supposed to return false after 300 seconds.

```java
        } else if (elapsed.elapsed(TimeUnit.SECONDS) > 300) {
          return false;
        }
```

And then for example, we have code like this to call `failBuildErrors()`.

```java
    if (checkBuildErrors) {
      waitUntilNoBuildErrors();
      // changed from specific projects to see all possible errors
      failIfBuildErrors("Imported projects have errors");
    }
```

**Comment by elharo** [comment]
It could be some issue with the combination of Eclipse 4.9/Java 11. That's where this regularly broke (not failed).

300 seconds is probably way too long. Perhaps we could just drop that to 120 seconds.

**Comment by chanseokoh** [comment]
Maybe `waitUntilNoBuildErrors()` accept a timeout value. My memory is hazy, but it is possible that I set it to 300 seconds on purpose. One place where this is used is an integration test importing a project. And I remember importing a Spring Boot projects can really take a lot of time since it often has to download a ton of dependencies if .m2 repo is empty. And building the entire project can also take a considerable amount of time in slow CI/CE environment.

**Comment by JoeWang1127** [comment]
close as obsolete.
