### ISSUE TITLE
DevServer - App does not starts on target JDK 1.8 and gives Unrecognized option: --add-opens errors

### ISSUE THREAD

**Issue by lokios** [GoogleCloudPlatform/google-cloud-eclipse#3740]
Can we add support for RunConfiguration: This is a new variable introduced in app-enging-core so that we can specify: 1.8 for example.
Variable :
  projectJdkVersion

This error is displayed when we 
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

NOTE: this happens when we run Eclipse with  Java 11 ; and want to run the appengine devserver in JDK 1.8

**Comment by suztomo** [comment]
It's similar to the problem fixed by https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/917, which was fixed and released as 0.9.10.

The latest release of this repository v1.10.1B already uses appengine-plugins-core 0.9.11. https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.10.1B/pom.xml#L101C1-L106C18

```
    <dependency>
      <!-- bundle: com.google.cloud.tools.appengine -->
      <groupId>com.google.cloud.tools</groupId>
      <artifactId>appengine-plugins-core</artifactId>
      <version>0.9.11</version>
    </dependency>
```

This change in appengine-plugins-core might require some tweak at the caller.

@lokios Which version of google-cloud-eclipse do you use?

**Comment by lokios** [comment]
Hi @suztomo, i am using  latest Google Cloud Platform for Eclipse i.e.	1.10.1.202306072020	

Yes you are correct that pom.xml already has latest dependency of : app-engine-core
   <artifactId>appengine-plugins-core</artifactId>
      <version>0.9.11</version>

However in your eclipse plugin there is no way to pass the new variable:
projectJdkVersion
which is recenty introduced by 0.9.11 plugin

Due to this limitation i am unable to run JDK 1.8 based projects as its giving : Unrecognized option: --add-opens
as add-opens is only supported from JDK 1.9

Please tell us how we can pass : projectJdkVersion variable with value 1.8 from the latest plugin?

Thanks

**Comment by diegomarquezp** [comment]
Closing as not planned as App Engine applications running on JDK 1.8 have reached end of support
