### ISSUE TITLE
Notify the user if deploy uses the generated version

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#470]
If the version is not specified in the appengine-web.xml, the deploy will rely on the backend to generate a new version for the deployment based on date and time. This might be something the user do not want to, so it would be nice if we would add a message to the message console showing the deploy output that explains how the user can avoid the usage of this generated version by setting the version in the xml.

**Comment by chanseokoh** [comment]
Eventually I imagine there will be a deploy configuration UI, where users can choose to either enter a custom version or let gcloud auto-generate one. This is what IntelliJ is currently doing.

**Comment by chanseokoh** [comment]
This is now handled in a much better way as explained in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/470#issuecomment-235692350 (not to mention we no longer set a version in `appengine-web.xml`). I don't think we need a message in the console, since we always bring up the deploy dialog. Closing.
