### ISSUE TITLE
Deployment doesn't update HTML

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#585]
Might be an App Engine server caching issue but until we can establish that:
1. Create new app engine project with wizard
2. deploy
3. Verify contents of index.html on https://1-dot-projectid.appspot.com
4. Edit index.html
5. deploy again
6. Look at https://1-dot-projectid.appspot.com and see that it has not changed. 

OTOH if the servlet java file is changed, the redeployed servlet does show the changes.

**Comment by patflynn** [comment]
did you try ctrl+F5 on the page to make sure you weren't getting a cached
version?

**Comment by elharo** [comment]
This is still happening, and even loading into a new browser that hasn't seen the page before doesn't help it.

I've verified in the cloud console that the new HTML file *is* uploaded. However, the old one is still there and served preferentially. This may well be an issue in gcloud or on the server side.

**Comment by chanseokoh** [comment]
This doesn't happen to me. Modification to the static `index.html` of our native Hello World is reflected almost instantly. @elharo I wonder if you were looking at a URL for a specific version, such as `https://20161107t114951-dot-<project>-1259.appspot.com/`.

**Comment by chanseokoh** [comment]
> Look at https://1-dot-projectid.appspot.com and see that it has not changed.

Reading the issue description again, I think you are looking at the specific version "1". Try `<project-id>.appspot.com`.

**Comment by elharo** [comment]
seems to be working now. Will reopen if I see it again.

**Comment by israellev** [comment]
I have also this problem, I tryied to refresh with ctrl+R and the changes in static files (css) not affect - checked the source in chrome.

**Comment by briandealwis** [comment]
@israellev that usually happens when using a URL that does not correspond to the service+version deployed.  If you open the [App Engine dashboard from the Cloud Console](https://console.cloud.google.com/appengine), and check out the recent dashboard activity in the _Info Panel_ on the right side, you should see something like the following:

![screen shot 2018-08-20 at 2 15 06 pm](https://user-images.githubusercontent.com/202851/44358791-fd2c2580-a483-11e8-938e-0d520ab22d7e.png)

You can then use the _Versions_ screen to open the specifically deployed service+version.

You can view the deployed files from [StackDriver Debug](https://console.cloud.google.com/debug).

If you're certain you have the right service+version, then it's likely a project configuration issue.  Under the hood, CT4E generates an _exploded war_ and then invokes the Cloud SDK to do the actual deploy.  We store the last two deployments in the `<workspace>/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp` directory.  There will be two directories there named something like `1530245133808` (the timestamp of your last deploy). The contents of the `staging-work/exploded-war` directory is the exploded war that is deployed.  If the files there are incorrect then your project's _Deployment Assembly_ (from the project properties) has likely become misconfigured.

**Comment by tsloan1377** [comment]
This issue seems to still be happening. 
For me, it's an html file that doesn't properly get updated when the project is built, despite using the --version tag to be sure the same version is being updated.
The correct version of the html file is shown in the StackDriver Debug index of deployed files, however when the app is run, it still refers to the old version of the file. 

My workaround so far is removing the staging bucket, and re-deploying the folder entirely, is there a better workaround or way to avoid this problem?

**Comment by mehmetalianil** [comment]
This might be a long shot, but I will take my chances.
In my case, this was resolved if I **built the project and then deployed it** to GCloud. 
I am not well versed in webdev, therefore I assumed that GC would build it during deploying it.
