### ISSUE TITLE
Enable specifying debug port the dev app server

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#68]
When the dev app server is launched in debug mode, it uses a random port the bind the debug port. We should allow the user to specify the debug port as part of the launch configuration. If the port is specified, it should be used in `com.google.cloud.tools.eclipse.appengine.localserver.server.CloudSdkLaunchConfigurationDelegate.getDebugPort()`

**Comment by elharo** [comment]
consider whether we should just find an available port and use that, rather than letting user choose

**Comment by briandealwis** [comment]
I assume this issue is referencing the Java Debug Interface port (JDI).  This may have made sense when we were using a Remote Attach to connect to the JVMs.  But since we now launch in a Remote Connect operation (where the JVMs connect to our debug session at a configured port), I can't think of any real benefit.  Feel free to re-open.
