### ISSUE TITLE
Allow the specification of the --host address as part of local run

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/google-cloud-eclipse#775]
dev_appserver.py has the following argument:

  --host HOST           host name to which application modules should bind
                        (default: localhost)

We should allow the user to change this. A common use-case is to set the host to 0.0.0.0, which then binds to localhost but allows the host to be hit from another machine.

**Comment by chanseokoh** [comment]
Turns out that the _Run On Server_ dialog already has the field _Server's host name_. I verified that we are actually ignoring whatever value entered in the field (when allowed to enter non-local hosts), so it's just a matter of retrieving the user-specified host and pass it to `dev_appserver.py` through `--host`.

![selection_002](https://cloud.githubusercontent.com/assets/10523105/19206626/3167f1f2-8cb8-11e6-9945-eb89fcb904ec.png)
