### ISSUE TITLE
Puzzling title for deployment configuration dialog

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#779]
The deployment dialog titling is a bit puzzling:

![screen shot 2016-10-06 at 3 15 56 pm](https://cloud.githubusercontent.com/assets/202851/19166994/d5f881be-8bd7-11e6-9113-38ad29104cee.PNG)

Since I had just issued a _deploy_, the titling should indicate that I'm about to deploy.  Maybe:

  - dialog title: "Deploy to App Engine Standard"
  - title area: "Configure deployment parameters for {1}"

I also wondered if the _OK_ button should be _Deploy_.

The widget spacing is also odd.

**Comment by chanseokoh** [comment]
I agree on the odd widget spacing. It's because of this line: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java#L117

The above spacing setting affects all the controls in the pane, so changing the spacing here will impact everything.

Particularly, the spacing between

- 'Account:' and 'Project ID:'
- 'Stop previous version' and '> Advanced'

looks too close.

**Comment by elharo** [comment]
Let's hold off on futzing with the spacing until we get a real UI expert to look at it. I suspect they're going to want a lot more changes than this, and whatever we do now is likely to be replaced.

**Comment by elharo** [comment]
Yes, the OK button should be "Deploy". Thanks for noticing that. Users are less likely to make a mistake when buttons are labelled with descriptive action verbs rather than generic Yes/No/OK/Cancel.

**Comment by elharo** [comment]
I'm removing the beta blocker label here. I'd like to reserve that for

A) Mandatory features
B) Outright bugs

**Comment by elharo** [comment]
How about:

dialog title: "Deploy to App Engine Standard"
title area: "Configure deploy parameters for {1}"

"Deploy" is a verb and "Deployment" is a noun, but deployment is an common word in English. 

We probably shouldn't bike shed too much over this.
