### ISSUE TITLE
Redundant facet support declaration of App Engine runtime

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#930]
In `.appengine.facet`, we declare that any runtime supports App Engine Standard facet for any version: [link](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml#L39)

In `.appengine.localserver`, we declare that the App Engine runtime supports App Engine Standard facet version 1: [link](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml#L69)

The latter is unnecessary code.

**Comment by elharo** [comment]
Is it true that any runtime supports the App Engine Standard facet? Maybe it's the first plugin.xml that's incorrect.

**Comment by chanseokoh** [comment]
> Is it true that any runtime supports the App Engine Standard facet?

Yes, at the current state, any server (e.g., Tomcat) can run our AE-S faceted projects, if that's what you're asking. @akerekes said that this is what we want to do. If we remove the first one, only our AE server can run AE-S faceted projects.

**Comment by briandealwis** [comment]
I go around and around on this.  With our current implementation, the answer is yes.  Our facet _currently_ ensures that (1) an `appengine-web.xml` exists (or is created), and (2) the project is configured to use the App Engine Standard runtime (providing a servlet and jsp jars).

(1) isn't strictly necessary.  After all, a developer could create a normal Dynamic Web Module v2.5 (`jst.web`) and configure their own `appengine-web.xml` _without_ our facet.  And providing they don't use any forbidden JRE classes, that module should work fine in App Engine Standard.

(2) provides the real benefit of our facet.  Because WTP makes it hard to associate runtimes to projects, and it doesn't provide default runtimes for basic web modules, our behaviour is a win.  But this function seems at odds with the other facets which indicate requirements and prevent the module from being run on inappropriate servers.

I wonder if we may want two facets.  The first facet could indicate compatibility: has an `appengine-web.xml`, uses the safe subset of the JRE.  The other facet would indicate that it's specific to App Engine Standard: it uses App Engine services and APIs.

**Comment by patflynn** [comment]
I think that it's true that only an AE server can run an AE standard
project.  It doesn't make a lot of sense to me to run a project with an
appengine-web.xml on Tomcat.

**Comment by akerekes** [comment]
How about migration/experiments the users want to do? I think we should not prevent them run an AE Standard project on Tomcat, provided it has what Tomcat needs (web.xml) and no AE API dependency.

**Comment by patflynn** [comment]
Won't the fact that the app has a web.xml give it a 'web' facet that makes
it runnable on Tomcat?  Why do we need to explicitly support that from our
facet?

**Comment by chanseokoh** [comment]
What I can tell from my testing, we need the following support declaration about our facet. Otherwise, trying to select Tomcat to run our project shows an error message that Tomcat doesn't support our facet. (This is just a declaration. We don't implement anything to make Tomcat support AE-S faceted projects.)

> In .appengine.facet, we declare that any runtime supports App Engine Standard facet for any version

**Comment by patflynn** [comment]
To me that message sounds appropriate. Tomcat does not support our
appengine-web.xml.

**Comment by chanseokoh** [comment]
I think this issue is in conflict with #254. #254 says our AE-S faceted projects should not be allowed to run on, say, Tomcat, as @patflynn suggests.

In that case, we should remove the first facet declaration in `.appengine.facet` and leave the second declaration in `.appengine.localserver` (i.e., the exact opposite of #931 and what this issue suggests).

**Comment by chanseokoh** [comment]
I believe we made a decision. We allow other compatible servers (i.e., Servlet 2.5 and Java 1.7) such as Tomcat to run App Engine projects (i.e., projects with the App Engine facet).

**Comment by chanseokoh** [comment]
As a record, this is what I found:

- **Declaration A**: In `.appengine.facet`, we declare that any runtime supports App Engine Standard facet for any version: [link](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml#L39)

- **Declaration B**: In `.appengine.localserver`, we declare that the App Engine runtime supports App Engine Standard facet version 1: [link](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/plugin.xml#L69)

Declaration A | Declaration B | Effect
:---: | :---: | ---
YES | YES | Both App Engine server and Tomcat can run App Engine faceted-projects. This is the current state.
YES | NO | Ditto (i.e., Declaration B is redundant)
NO | YES | Only App Engine server can run App Engine faceted-projects.
NO | NO |  No server can run App Engine faceted-projects.

So, I suggested to remove Declaration B by opening this issue. However, @nbashirbello feels very uncomfortable about removing it considering the complexity of configuring WTP (basically, [if it ain't broke, don't fix it](https://en.wikipedia.org/wiki/If_it_ain%27t_broke,_don%27t_fix_it)), so I'll close this issue.
