### ISSUE TITLE
Hamcrest jars in release

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#988]
Our release build bundles in 3 hamcrest jars. These should only be needed for tests, not for the production code. Can we get rid of them?

**Comment by elharo** [comment]
http://stackoverflow.com/questions/33545438/adding-test-only-dependencies-for-non-osgi-junit-test-in-a-tycho-project

**Comment by elharo** [comment]
I don't see references to hamcrest in any non-test bundles.

**Comment by briandealwis** [comment]
It's being pulled in from our internal `com.google.cloud.tools.eclipse.3rdparty.feature` feature.  We're using it to pull in third-party jars that come from Maven Central (and hence aren't readily available otherwise).  I think we should be able to get rid of them from the feature and instead reference them directly from our .target files.
